### ISSUE TITLE
Error when press "Go Live"

### ISSUE THREAD

**Issue by Nuttavoot** [adilinden-oss/octoprint-webcamstreamer#36]
This is the error I got "
WebcamStreamer Error
404 Client Error: Not Found ("pull access denied for adilinden/rpi-ffmpeg, repository does not exist or may require 'docker login': denied: requested access to the resource is denied")"

But successfully run "docker run hello-world"

**Comment by ppetrov-dev** [comment]
I have the same error. Let's wait for the author together=)

**Comment by JoshJames04** [comment]
After having the same issue time and time again, I done some digging. In this, I found that the "rpi-ffmpeg" docker file no longer exists on adilinden's docker page. If this is intentional by adilinden or not. But it certainly prevents anyone from setting up the webcam streamer in the future. With any luck, this is a mistake, he will see this, and then he will re-upload it.

**Comment by kolisko** [comment]
+1

**Comment by kolisko** [comment]
I fixed the rpi-ffmpeg Dockerfile and created the pull request https://github.com/adilinden-oss/docker-ffmpeg/pull/1. Until PR will not be merged here is the workaround - you can pull docker image kolisko/rpi-ffmpeg instead the missing official one and change the WebcamStreamer Plugin/Advanced Settings/Docker Image to that image kolisko/rpi-ffmpeg.

**Comment by ttrueten** [comment]
docker pull kolisko/rpi-ffmpeg runs well. Thank you.

T.

**Comment by adilinden** [comment]
https://hub.docker.com/r/adilinden/rpi-ffmpeg exists again.
